### ISSUE TITLE
Adding 4+ projects 

### ISSUE THREAD

**Issue by ilovemybeautii** [onyx1/scalable-lightbox#1]
Hello, I am currently using your plug-in and did everything correctly however when I add four more id's or divs the plugin becomes broken.  Is this normal? `<div id="projects-container" class="clearfix">

  <a class="project-item" href="#1">
    <div class="img">
      <img src="images/diaper-infographic" />
    </div>
    <div class="caption">
      <h3>From Baby's Bottoms to Landfills</h3>
    </div>
  </a>

  <a class="project-item" href="#2">
    <div class="img">
      <img src="images/dyson" />
    </div>
    <div class="caption">
      <h3>Dyson Object Study</h3>
    </div>
  </a>

  <a class="project-item" href="#3">
    <div class="img">
      <img src="images/type3.jpg" />
    </div>
    <div class="caption">
      <h3>Typography Three: Expressive and Experimental</h3>
    </div>
  </a>

  <a class="project-item" href="#4">
    <div class="img">
      <img src="images/medialaw.jpg" />
    </div>
    <div class="caption">
      <h3>Media Business Law Collatral</h3>
    </div>
  </a>

  <a class="project-item" href="#5">
    <div class="img">
      <img src="images/art-direction.jpg" />
    </div>
    <div class="caption">
      <h3>Publication Design</h3>
    </div>
  </a>

```
<a class="project-item" href="#6">
<div class="img">
  <img src="images/navy-pier.jpg" />
</div>
<div class="caption">
  <h3>Poster Design</h3>
</div>
```

  </a>

```
<a class="project-item" href="#7">
<div class="img">
  <img src="images/hilton-publication-cover.jpg" />
</div>
<div class="caption">
  <h3>Annual Report Design - Hilton Worldwide</h3>
</div>
```

  </a>

```
<a class="project-item" href="#8">
<div class="img">
  <img src="images/dyson" />
</div>
<div class="caption">
  <h3>Dyson Object Study</h3>
</div>
```

  </a>

```
<a class="project-item" href="#9">
<div class="img">
  <img src="images/dyson" />
</div>
<div class="caption">
  <h3>Dyson Object Study</h3>
</div>
```

  </a>

```
<a class="project-item" href="#10">
<div class="img">
  <img src="images/dyson" />
</div>
<div class="caption">
  <h3>Dyson Object Study</h3>
</div>
```

  </a>

```
<a class="project-item" href="#11">
<div class="img">
  <img src="images/dyson" />
</div>
<div class="caption">
  <h3>Dyson Object Study</h3>
</div>
```

  </a>

```
<a class="project-item" href="#12">
<div class="img">
  <img src="images/dyson" />
</div>
<div class="caption">
  <h3>Dyson Object Study</h3>
</div>
```

  </a>

</div>

<script type="text/javascript">
$(function() {

  // initialize ScalableLightbox
  $.ScalableLightbox({
    // show what's happening in
    // the debugger console
    debug:        true,

    // define the path for all
    // resources (images):
    baseImgPath:  '/assets/img/lightbox/',

    // define data structure inline
    data: [
      // canyon house (deck id 1)
      { "id": 1,
        "items": [
          {
            "img": "canyon-house/01.jpg",
            "width": 1500,
            "height": 2173,
            "caption": "Canyon House 01.jpg by <a href=\"http://www.labics.it\" target=\"_blank\">Labics</a>"
          },
          {
            "img": "canyon-house/04.jpg",
            "width": 1500,
            "height": 1033,
            "caption": "Canyon House 04.jpg by <a href=\"http://www.labics.it\" target=\"_blank\">Labics</a>"
          },
          {
            "img": "canyon-house/03.jpg",
            "width": 1500,
            "height": 2173,
            "caption": "Canyon House 03.jpg by <a href=\"http://www.labics.it\" target=\"_blank\">Labics</a>"
          }
          // additional item objects ...
        ]
      },
      
      
      // italpromo (deck id 2)
      { "id": 2,
        "items": [
          {
            "img": "italpromo/01.jpg",
            "width": 1500,
            "height": 2173,
            "caption": "Italpromo 01.jpg by <a href=\"http://www.labics.it\" target=\"_blank\">Labics</a>"
          },
          {
            "img": "italpromo/04.jpg",
            "width": 1500,
            "height": 751,
            "caption": "Italpromo 04.jpg by <a href=\"http://www.labics.it\" target=\"_blank\">Labics</a>"
          },
          {
            "img": "italpromo/05.jpg",
            "width": 1500,
            "height": 1033,
            "caption": "Italpromo 05.jpg by <a href=\"http://www.labics.it\" target=\"_blank\">Labics</a>"
          }
          // additional item objects ...
        ]
      }
    ],
    // set index layout to masonry
    index: {
      layout:     "masonry"
    }
  });

  // define click behavior by employing
  // the open method
  $(".project-item").click(function(e) {

    // get the deck id of the current item
    var id = parseInt($(this).attr("href").substring(1), 15);

    // prevent the default anchor behavior
    e.preventDefault();

    // open the lightbox module
    $.ScalableLightbox("open", { module: "lightbox", deck: id });

  });

});

</script>

`

**Comment by onyx1** [comment]
Hey there, this should not happen. Could you please provide your code in a [codepen]( http://codepen.io/)? Thank you.
